/**
 * strings.js — every interface string, in each supported language.
 *
 * Inlined into dist/index.html by scripts/build.mjs. Level and glossary text
 * live elsewhere (levels/ and i18n/). `{0}`, `{1}` are placeholders.
 * Keys ending in "Html" are trusted markup; everything else is plain text.
 * Arrays are pools the Cat picks from at random.
 *
 * To add a language: copy the `en` block, translate it, add the code to
 * LANGS below, and add i18n/<code>/ with the level overlays and glossary.
 */
(function (root) {
  "use strict";

  const LANGS = [
    { code: "pt", label: "Português", short: "PT", html: "pt-BR", locale: "pt-BR" },
    { code: "es", label: "Español", short: "ES", html: "es", locale: "es" },
    { code: "en", label: "English", short: "EN", html: "en", locale: "en" },
  ];

  const pt = {
    skip: "Pular para o conteúdo",
    brandAria: "Cheshire — início",
    navAria: "Principal",
    navHome: "Fases",
    navLab: "Laboratório",
    navGlossary: "Glossário",
    navAbout: "Sobre",
    xpTitle: "Pontos de experiência",
    themeToLight: "Mudar para tema claro",
    themeToDark: "Mudar para tema escuro",
    menuOpen: "Abrir menu",
    langAria: "Idioma",
    titleHome: "Cheshire — física quântica na prática",
    titleSuffix: "{0} · Cheshire",

    heroKicker: "⚛ minijogo educativo · código aberto",
    heroTitleHtml: "Física quântica, <em>na prática</em>.",
    heroLede: "Monte circuitos, meça qubits e veja a interferência acontecer. Fases curtas para quem está só curioso e para quem quer ir fundo.",
    heroLab: "Abrir o laboratório",
    heroSphereAria: "Esfera de Bloch animada: uma seta girando representa o estado de um qubit",
    ctaStart: "Começar a primeira fase",
    ctaContinue: "Continuar: {0}",
    ctaResume: "Retomar: {0} (passo {1})",
    ctaReview: "Rever as fases",
    homeWho: "Pra quem?",
    homeAudAria: "Filtrar fases por público",
    homeLevels: "fases",
    homeStars: "estrelas",
    homeTrack: "trilha {0}",
    homeSoon: "em breve",
    homeNext: "próxima",
    homeInProgress: "em andamento",
    homeNone: "Nenhuma fase para este público ainda. Que tal escrever uma?",
    cardStars: ", {0} estrelas",
    dykTitle: "Você sabia?",
    dykNext: "Outra curiosidade",
    dykFrom: "Da fase ",
    starsOf: "{0} de 3 estrelas",

    tracks: {
      fundamentos: ["Fundamentos", "Qubits, medição e a estranheza básica."],
      circuitos: ["Circuitos", "Portas, fase, interferência e emaranhamento na prática."],
      fenomenos: ["Fenômenos", "Experimentos reais da física quântica, em forma de circuito."],
      algoritmos: ["Algoritmos e protocolos", "O que dá para fazer com tudo isso."],
    },
    audience: {
      todos: ["Todos", "Todas as fases, na ordem sugerida.", "Todos"],
      curioso: ["🌱 Curioso(a)", "Zero pré-requisito. Só curiosidade.", "Curioso(a)"],
      estudante: ["📘 Estudante", "Ensino médio ou graduação: um pouco de vetor e ângulo ajuda.", "Estudante"],
      avancado: ["🚀 Avançado", "Para devs e pesquisadores: algoritmos e protocolos.", "Avançado"],
    },
    gates: {
      H: ["Hadamard", "cria superposição — troca polos por equador."],
      X: ["Pauli-X", "o NOT quântico — troca 0 e 1."],
      Y: ["Pauli-Y", "meia volta em torno do eixo Y."],
      Z: ["Pauli-Z", "inverte a fase de |1⟩ (meia volta no equador)."],
      S: ["Fase S", "gira a fase de |1⟩ em 90°."],
      T: ["Fase T", "gira a fase de |1⟩ em 45°."],
      SDG: ["S adjunta", "gira a fase em −90°."],
      TDG: ["T adjunta", "gira a fase em −45°."],
      CNOT: ["NOT controlado", "se o controle (●) é 1, aplica X no alvo (⊕)."],
      CZ: ["Z controlada", "inverte o sinal de |11⟩."],
      SWAP: ["Troca", "troca o estado de dois qubits."],
    },

    legendTitle: "A cor de cada barra mostra a fase da amplitude",
    legend: "cor = fase",
    stateNow: "Estado atual",
    ketAria: "Estado em notação de Dirac",
    ghostNote: "Contorno tracejado = alvo.",
    targetTitle: "Alvo: {0}",
    sphereOne: "Esfera de Bloch",
    spherePerQubit: "Um qubit de cada vez",
    entangled: "emaranhado",
    arrowLen: "seta {0}%",
    blochAria: "Esfera de Bloch: x {0}, y {1}, z {2}",

    paletteAria: "Portas disponíveis",
    boardAria: "Circuito quântico",
    clear: "Limpar",
    pendingHtml: "<b>{0}</b>: agora clique no fio do <b>{1}</b>, na mesma coluna. <span class=\"dim\">Esc cancela.</span>",
    pendingTarget: "alvo (⊕)",
    pendingSecond: "segundo qubit",
    helpTwo2: "Clique no fio do controle; o outro fio vira o alvo.",
    helpTwoN: "Clique no fio do controle e depois no alvo.",
    helpOne: "Clique num espaço do fio.",
    helpNone: "Escolha uma porta acima. Clique numa porta já colocada para removê-la.",
    gateLocked: "Essa porta faz parte do desafio e não pode sair.",
    pickFirst: "Escolha uma porta na paleta primeiro.",
    wireBusy: "O outro fio já está ocupado nessa coluna.",
    cellEmpty: "{0}, coluna {1}: vazio",
    cellGate: "{0}, coluna {1}: {2}",
    cellFixed: " (fixa)",
    cellRemove: " — clique para remover",
    gateCount1: "{0} porta",
    gateCountN: "{0} portas",

    playerBack: "← Fases",
    playerBackAria: "Voltar ao mapa de fases",
    stepEnd: "fim",
    next: "Continuar",
    nextFinish: "Concluir fase",
    nextOver: "Fim da fase",
    resumed: "Retomando do passo {0}.",
    kickerQuiz: "Pergunta",
    kickerCircuit: "Desafio",
    kickerMeasure: "Experimento",
    kickerPredict: "Palpite",
    factSource: "Fonte: {0}",
    quizFirst: "Na primeira! +1 ponto",
    quizAfter: "Isso! Agora você sabe o porquê.",
    quizWrong: "Quase! Leia o porquê e tente outra.",
    goalTag: "Alvo",
    yourCircuit: "Seu circuito",
    solvedGaveUp: "Solução aplicada. Estude o circuito e siga em frente.",
    solvedFewer: "Resolvido com {0} portas — menos que a nossa solução! 🤯",
    solvedPerfect: "Resolvido de primeira, com o mínimo de portas! ✨",
    solved: "Resolvido!",
    solvedMore1: "Resolvido! Dá para fazer com {0} porta.",
    solvedMoreN: "Resolvido! Dá para fazer com {0} portas.",
    targetHit: "Alvo atingido. ",
    phaseOffHtml: "As probabilidades batem… mas a <strong>fase</strong> não. Olhe as cores das barras e a esfera.",
    fidelity: "Quase lá? Fidelidade com o alvo: {0}%",
    hint: "💡 Dica",
    hintN: "💡 Dica ({0}/{1})",
    hintSolution: "🔓 Ver solução",
    hintLabel: "Dica {0}: ",
    measureNone: "Nenhuma medição ainda.",
    measureSeqAria: "Últimos resultados",
    measureOne: "O qubit “caiu” para este resultado.",
    measureMany: "Último de {0} resultados.",
    measureDone: "Continue medindo à vontade — ou siga em frente.",
    measureReset: "Zerar",
    measureCleared: "Contagem zerada.",
    measure1: "Medir 1×",
    theCircuit: "O circuito",
    measurements: "Medições",
    measureShortcut: "atalho: espaço",
    progress: "Progresso",
    measureExpected: "Tracejado = o que a teoria prevê. Quanto mais medições, mais perto as barras chegam dele.",
    predictAny: "{0} (· = tanto faz)",
    predictConfirm: "Confirmar palpite",
    predictAria: "Seu palpite, em porcentagem",
    verdict1: "Na mosca! 🎯",
    verdict2: "Muito perto! 👏",
    verdict3: "Chegou perto.",
    verdict4: "Surpresa, né? 😮",
    predictYours: "Seu palpite: {0}",
    predictAnswer: "Resposta: {0}",
    predictP1: "+1 ponto pela intuição quântica",
    predictP05: "+½ ponto",
    predictP0: "Sem ponto desta vez — mas agora você sabe!",
    predictChance: "Qual a chance?",
    predictOf: "de medir {0}",
    finishMastered: "Fase dominada!",
    finishDone: "Fase concluída!",
    finishRecord: "{0} XP (seu recorde é {1})",
    finishTake: "Para levar",
    finishTerms: "Termos desta fase",
    finishFurther: "Para ir além",
    finishNext: "Próxima: {0}",
    finishAgain: "Jogar de novo",
    finishMap: "Mapa de fases",
    finishThree: "Três estrelas! ⭐⭐⭐",
    finishTip: "Dica: acerte de primeira e use menos portas para mais estrelas.",

    labTitle: "Laboratório livre",
    labDesc: "Sem objetivo, sem nota: monte o circuito que quiser (até 4 qubits) e veja o estado mudar em tempo real. Bom para testar ideias das fases.",
    labLoad: "Carregar exemplo",
    labLess: "Menos qubits",
    labMore: "Mais qubits",
    labQ1: "{0} qubit",
    labQN: "{0} qubits",
    presets: {
      vazio: "Circuito vazio", bell: "Par de Bell", ghz: "GHZ (3 qubits)", interferencia: "Interferência (H·Z·H)",
      grover: "Grover (marca |11⟩)", teleporte: "Teletransporte",
    },
    glossTitle: "Glossário",
    glossDesc: "As palavras que aparecem nas fases, explicadas sem fórmula (quase).",
    glossSearch: "Buscar termo…",
    glossSearchAria: "Buscar no glossário",
    glossNone: "Nada encontrado.",
    aboutTitle: "Sobre o Cheshire",
    aboutLede: "Um minijogo aberto para ensinar computação e física quântica a pessoas diferentes, em níveis diferentes — do “nunca ouvi falar” ao “quero entender Grover”.",
    aboutHtml: `
<h2>Por que “Cheshire”?</h2>
<p>Em <em>Alice no País das Maravilhas</em> (Lewis Carroll, 1865), o Gato de Cheshire some aos poucos até sobrar só o sorriso — e Alice comenta que já viu muito gato sem sorriso, mas nunca um sorriso sem gato. É o seu companheiro aqui: ele comenta suas jogadas, dá pistas e, se você ficar parado, desaparece deixando só o sorriso. Clique nele para ouvir uma curiosidade.</p>
<p>A física também tem o seu: em 2013, Aharonov, Popescu, Rohrlich e Skrzypczyk propuseram o <strong>gato de Cheshire quântico</strong> — num interferômetro, medições fracas indicam que a partícula passou por um caminho e o seu spin, por outro. Em 2014 o efeito foi observado com nêutrons, e o que ele significa ainda é debatido.</p>
<p><button class="btn small" data-action="pet-toggle"></button></p>
<h2>E a esfera que gira?</h2>
<p>É a esfera de Bloch, homenagem a Felix Bloch: o jeito mais bonito de enxergar um qubit. Em todo desafio, a seta que você vê girando é ela.</p>
<h2>Como as fases funcionam</h2>
<p>Cada fase é um único arquivo JSON na pasta <code>levels/</code> do repositório. O motor lê esses arquivos no build e monta tudo num só HTML — sem servidor, sem rastreador, sem requisição a terceiros. Uma fase é uma sequência de passos:</p>
<div class="types">
  <div><b>story</b><span>Texto curto com ícone: contexto, história, explicação.</span></div>
  <div><b>quiz</b><span>Múltipla escolha, com o porquê de cada alternativa.</span></div>
  <div><b>circuit</b><span>Desafio: monte um circuito que chegue ao estado-alvo.</span></div>
  <div><b>measure</b><span>Meça um circuito várias vezes e veja a estatística surgir.</span></div>
  <div><b>predict</b><span>Chute a probabilidade antes de ver a resposta.</span></div>
  <div><b>fact</b><span>Uma curiosidade para lembrar depois.</span></div>
</div>
<p>Portas são escritas como texto — <code>"H 0"</code>, <code>"CNOT 0 1"</code> — e o validador do repositório roda a solução de referência de cada desafio no mesmo simulador do jogo. Nenhuma fase publicada é impossível. As traduções ficam em <code>i18n/</code> e só trocam o texto: a física é a mesma em todos os idiomas.</p>
<h2>Convenções</h2>
<p>O fio de cima é o qubit 0 e é o dígito mais à esquerda: em <code>|10⟩</code>, o qubit 0 vale 1. Nas barras de probabilidade, a <strong>cor</strong> mostra a fase de cada amplitude; nas esferas, uma seta curta significa que o qubit está emaranhado com os outros.</p>
<h2>Contribua</h2>
<p>Professor(a), estudante ou pesquisador(a)? Escreva uma fase ou traduza uma. O passo a passo está em <code>docs/CONTRIBUTING.md</code>, no <a href="https://github.com/2T0nnks/Cheshire" rel="noopener">repositório no GitHub</a>.</p>
<h2>Privacidade</h2>
<p>Seu progresso fica só no seu navegador (localStorage). Nada é enviado a lugar nenhum.</p>
<p><button class="btn small" data-action="reset-progress">Apagar meu progresso</button></p>
<h2>Licenças</h2>
<p>Código do motor sob MIT; conteúdo das fases e documentação sob CC BY-SA 4.0. Fontes Space Grotesk, Atkinson Hyperlegible e JetBrains Mono sob SIL OFL.</p>`,
    resetConfirm: "Apagar todo o seu progresso neste navegador?",
    resetDone: "Progresso apagado.",
    footerLeftHtml: "Cheshire · aprenda quântica brincando · <a href=\"https://github.com/2T0nnks/Cheshire\" rel=\"noopener\">código no GitHub</a>",
    footerRight: "Feito com qubits simulados e muito café ☕",

    petAria: "Gato de Cheshire — clique para ouvir uma curiosidade",
    petHide: "Esconder o Gato",
    petShow: "Mostrar o Gato",
    petBack: "Voltei! Nunca fui embora, na verdade.",
    petGreet: ["Olá! Por onde começar? Depende de aonde você quer chegar.", "Bem-vindo. Aqui nada é só uma coisa ou outra — até alguém olhar.", "Escolha uma fase. Eu te acompanho… às vezes só com o sorriso."],
    petLab: "Laboratório livre! Nada pode dar errado. Quer dizer… quase nada.",
    petStart: ["{0} {1}. Vamos nessa!", "Ah, “{1}”. Uma das minhas favoritas.", "Siga o coelho. Ou o circuito."],
    petQuizRight: ["Isso! Sorri de orelha a orelha.", "Exato. Até apareci inteiro de alegria.", "Na mosca. Você é bom nisso."],
    petQuizLate: "Aí sim. Errar faz parte da superposição.",
    petQuizWrong: ["Hmm, não foi dessa vez. Lê o porquê — eu espero.", "Cada vez mais curiosíssimo! Tenta outra.", "Nem tudo é o que parece. Tenta de novo."],
    petGaveUp: "Estude esse circuito com calma. Da próxima, é seu.",
    petFewer: "Menos portas que a solução oficial?! Até eu fiquei visível de surpresa.",
    petSolved: ["O Gato sorri: alvo atingido!", "Que circuito elegante.", "Perfeito. A seta foi exatamente aonde devia."],
    petPhase: "Psst: as barras batem, mas a cor não. É a fase!",
    petHint: "Psst… deixei uma dica logo abaixo do circuito.",
    petMeasure: "Caiu! Antes de medir, nem eu sabia o resultado.",
    petPredict1: "Que intuição quântica! Estou impressionado.",
    petPredict05: "Chegou perto. A quântica engana todo mundo.",
    petPredict0: "Surpreso? Eu também fiquei, da primeira vez.",
    petFinish3: "Três estrelas! Eu sabia — ou estava em superposição de saber.",
    petFinish: "Fase concluída! Quer tentar as três estrelas?",
    petLang: "Agora falo português. Um gato poliglota, quem diria.",
    petQuips: [
      "Aqui somos todos meio superpostos. Você também, até alguém olhar.",
      "Aonde você quer chegar? Isso depende bastante do circuito que você montar.",
      "Já vi muito gato sem sorriso. Mas qubit sem fase? Nunca.",
      "Se eu sumir, não se preocupe: é só decoerência.",
      "Cada vez mais curiosíssimo! É assim que se aprende quântica.",
      "Duas H seguidas se desfazem. Eu e o Chapeleiro também, depois do chá.",
    ],
  };

  const es = {
    skip: "Saltar al contenido",
    brandAria: "Cheshire — inicio",
    navAria: "Principal",
    navHome: "Niveles",
    navLab: "Laboratorio",
    navGlossary: "Glosario",
    navAbout: "Acerca de",
    xpTitle: "Puntos de experiencia",
    themeToLight: "Cambiar a tema claro",
    themeToDark: "Cambiar a tema oscuro",
    menuOpen: "Abrir menú",
    langAria: "Idioma",
    titleHome: "Cheshire — física cuántica en la práctica",
    titleSuffix: "{0} · Cheshire",

    heroKicker: "⚛ minijuego educativo · código abierto",
    heroTitleHtml: "Física cuántica, <em>en la práctica</em>.",
    heroLede: "Arma circuitos, mide qubits y mira cómo ocurre la interferencia. Niveles cortos para quien solo tiene curiosidad y para quien quiere ir a fondo.",
    heroLab: "Abrir el laboratorio",
    heroSphereAria: "Esfera de Bloch animada: una flecha que gira representa el estado de un qubit",
    ctaStart: "Empezar el primer nivel",
    ctaContinue: "Continuar: {0}",
    ctaResume: "Retomar: {0} (paso {1})",
    ctaReview: "Repasar los niveles",
    homeWho: "¿Para quién?",
    homeAudAria: "Filtrar niveles por público",
    homeLevels: "niveles",
    homeStars: "estrellas",
    homeTrack: "ruta {0}",
    homeSoon: "pronto",
    homeNext: "siguiente",
    homeInProgress: "en curso",
    homeNone: "Todavía no hay niveles para este público. ¿Y si escribes uno?",
    cardStars: ", {0} estrellas",
    dykTitle: "¿Sabías que…?",
    dykNext: "Otra curiosidad",
    dykFrom: "Del nivel ",
    starsOf: "{0} de 3 estrellas",

    tracks: {
      fundamentos: ["Fundamentos", "Qubits, medición y la rareza básica."],
      circuitos: ["Circuitos", "Puertas, fase, interferencia y entrelazamiento en la práctica."],
      fenomenos: ["Fenómenos", "Experimentos reales de física cuántica, en forma de circuito."],
      algoritmos: ["Algoritmos y protocolos", "Lo que se puede hacer con todo esto."],
    },
    audience: {
      todos: ["Todos", "Todos los niveles, en el orden sugerido.", "Todos"],
      curioso: ["🌱 Curioso(a)", "Sin requisitos previos. Solo curiosidad.", "Curioso(a)"],
      estudante: ["📘 Estudiante", "Secundaria o universidad: un poco de vectores y ángulos ayuda.", "Estudiante"],
      avancado: ["🚀 Avanzado", "Para devs e investigadores: algoritmos y protocolos.", "Avanzado"],
    },
    gates: {
      H: ["Hadamard", "crea superposición — cambia polos por ecuador."],
      X: ["Pauli-X", "el NOT cuántico — intercambia 0 y 1."],
      Y: ["Pauli-Y", "media vuelta alrededor del eje Y."],
      Z: ["Pauli-Z", "invierte la fase de |1⟩ (media vuelta por el ecuador)."],
      S: ["Fase S", "gira la fase de |1⟩ 90°."],
      T: ["Fase T", "gira la fase de |1⟩ 45°."],
      SDG: ["S adjunta", "gira la fase −90°."],
      TDG: ["T adjunta", "gira la fase −45°."],
      CNOT: ["NOT controlado", "si el control (●) es 1, aplica X al objetivo (⊕)."],
      CZ: ["Z controlada", "invierte el signo de |11⟩."],
      SWAP: ["Intercambio", "intercambia el estado de dos qubits."],
    },

    legendTitle: "El color de cada barra muestra la fase de la amplitud",
    legend: "color = fase",
    stateNow: "Estado actual",
    ketAria: "Estado en notación de Dirac",
    ghostNote: "Contorno punteado = objetivo.",
    targetTitle: "Objetivo: {0}",
    sphereOne: "Esfera de Bloch",
    spherePerQubit: "Un qubit a la vez",
    entangled: "entrelazado",
    arrowLen: "flecha {0}%",
    blochAria: "Esfera de Bloch: x {0}, y {1}, z {2}",

    paletteAria: "Puertas disponibles",
    boardAria: "Circuito cuántico",
    clear: "Borrar",
    pendingHtml: "<b>{0}</b>: ahora haz clic en el hilo del <b>{1}</b>, en la misma columna. <span class=\"dim\">Esc cancela.</span>",
    pendingTarget: "objetivo (⊕)",
    pendingSecond: "segundo qubit",
    helpTwo2: "Haz clic en el hilo de control; el otro hilo será el objetivo.",
    helpTwoN: "Haz clic en el hilo de control y luego en el objetivo.",
    helpOne: "Haz clic en un espacio del hilo.",
    helpNone: "Elige una puerta arriba. Haz clic en una puerta ya colocada para quitarla.",
    gateLocked: "Esa puerta es parte del desafío y no se puede quitar.",
    pickFirst: "Primero elige una puerta de la paleta.",
    wireBusy: "El otro hilo ya está ocupado en esta columna.",
    cellEmpty: "{0}, columna {1}: vacío",
    cellGate: "{0}, columna {1}: {2}",
    cellFixed: " (fija)",
    cellRemove: " — clic para quitar",
    gateCount1: "{0} puerta",
    gateCountN: "{0} puertas",

    playerBack: "← Niveles",
    playerBackAria: "Volver al mapa de niveles",
    stepEnd: "fin",
    next: "Continuar",
    nextFinish: "Terminar nivel",
    nextOver: "Fin del nivel",
    resumed: "Retomando desde el paso {0}.",
    kickerQuiz: "Pregunta",
    kickerCircuit: "Desafío",
    kickerMeasure: "Experimento",
    kickerPredict: "Predicción",
    factSource: "Fuente: {0}",
    quizFirst: "¡A la primera! +1 punto",
    quizAfter: "¡Eso! Ahora sabes por qué.",
    quizWrong: "¡Casi! Lee el porqué e intenta otra.",
    goalTag: "Objetivo",
    yourCircuit: "Tu circuito",
    solvedGaveUp: "Solución aplicada. Estudia el circuito y sigue adelante.",
    solvedFewer: "¡Resuelto con {0} puertas — menos que nuestra solución! 🤯",
    solvedPerfect: "¡Resuelto a la primera, con el mínimo de puertas! ✨",
    solved: "¡Resuelto!",
    solvedMore1: "¡Resuelto! Se puede hacer con {0} puerta.",
    solvedMoreN: "¡Resuelto! Se puede hacer con {0} puertas.",
    targetHit: "Objetivo alcanzado. ",
    phaseOffHtml: "Las probabilidades coinciden… pero la <strong>fase</strong> no. Mira los colores de las barras y la esfera.",
    fidelity: "¿Casi? Fidelidad con el objetivo: {0}%",
    hint: "💡 Pista",
    hintN: "💡 Pista ({0}/{1})",
    hintSolution: "🔓 Ver solución",
    hintLabel: "Pista {0}: ",
    measureNone: "Todavía no hay mediciones.",
    measureSeqAria: "Últimos resultados",
    measureOne: "El qubit “cayó” en este resultado.",
    measureMany: "Último de {0} resultados.",
    measureDone: "Sigue midiendo cuanto quieras — o continúa.",
    measureReset: "Reiniciar",
    measureCleared: "Conteo reiniciado.",
    measure1: "Medir 1×",
    theCircuit: "El circuito",
    measurements: "Mediciones",
    measureShortcut: "atajo: espacio",
    progress: "Progreso",
    measureExpected: "Punteado = lo que predice la teoría. Cuantas más mediciones, más se acercan las barras.",
    predictAny: "{0} (· = cualquiera)",
    predictConfirm: "Confirmar predicción",
    predictAria: "Tu predicción, en porcentaje",
    verdict1: "¡En el blanco! 🎯",
    verdict2: "¡Muy cerca! 👏",
    verdict3: "Cerca.",
    verdict4: "Sorpresa, ¿no? 😮",
    predictYours: "Tu predicción: {0}",
    predictAnswer: "Respuesta: {0}",
    predictP1: "+1 punto por intuición cuántica",
    predictP05: "+½ punto",
    predictP0: "Sin punto esta vez — ¡pero ahora lo sabes!",
    predictChance: "¿Qué probabilidad?",
    predictOf: "de medir {0}",
    finishMastered: "¡Nivel dominado!",
    finishDone: "¡Nivel completado!",
    finishRecord: "{0} XP (tu récord es {1})",
    finishTake: "Para llevar",
    finishTerms: "Términos de este nivel",
    finishFurther: "Para ir más allá",
    finishNext: "Siguiente: {0}",
    finishAgain: "Jugar de nuevo",
    finishMap: "Mapa de niveles",
    finishThree: "¡Tres estrellas! ⭐⭐⭐",
    finishTip: "Consejo: acierta a la primera y usa menos puertas para más estrellas.",

    labTitle: "Laboratorio libre",
    labDesc: "Sin objetivo, sin nota: arma el circuito que quieras (hasta 4 qubits) y mira cómo cambia el estado en tiempo real. Ideal para probar ideas de los niveles.",
    labLoad: "Cargar ejemplo",
    labLess: "Menos qubits",
    labMore: "Más qubits",
    labQ1: "{0} qubit",
    labQN: "{0} qubits",
    presets: {
      vazio: "Circuito vacío", bell: "Par de Bell", ghz: "GHZ (3 qubits)", interferencia: "Interferencia (H·Z·H)",
      grover: "Grover (marca |11⟩)", teleporte: "Teletransporte",
    },
    glossTitle: "Glosario",
    glossDesc: "Las palabras que aparecen en los niveles, explicadas sin fórmulas (casi).",
    glossSearch: "Buscar término…",
    glossSearchAria: "Buscar en el glosario",
    glossNone: "No se encontró nada.",
    aboutTitle: "Acerca de Cheshire",
    aboutLede: "Un minijuego abierto para enseñar computación y física cuántica a personas distintas, en niveles distintos — del “nunca lo oí” al “quiero entender Grover”.",
    aboutHtml: `
<h2>¿Por qué “Cheshire”?</h2>
<p>En <em>Alicia en el País de las Maravillas</em> (Lewis Carroll, 1865), el Gato de Cheshire desaparece poco a poco hasta que solo queda su sonrisa — y Alicia comenta que ha visto muchos gatos sin sonrisa, pero nunca una sonrisa sin gato. Aquí es tu compañero: comenta tus jugadas, da pistas y, si te quedas quieto, desaparece dejando solo la sonrisa. Haz clic en él para oír una curiosidad.</p>
<p>La física también tiene el suyo: en 2013, Aharonov, Popescu, Rohrlich y Skrzypczyk propusieron el <strong>gato de Cheshire cuántico</strong> — en un interferómetro, mediciones débiles indican que la partícula pasó por un camino y su espín, por otro. En 2014 el efecto se observó con neutrones, y lo que significa todavía se debate.</p>
<p><button class="btn small" data-action="pet-toggle"></button></p>
<h2>¿Y la esfera que gira?</h2>
<p>Es la esfera de Bloch, homenaje a Felix Bloch: la forma más bonita de ver un qubit. En cada desafío, la flecha que ves girar es ella.</p>
<h2>Cómo funcionan los niveles</h2>
<p>Cada nivel es un único archivo JSON en la carpeta <code>levels/</code> del repositorio. El motor lee esos archivos al compilar y arma todo en un solo HTML — sin servidor, sin rastreadores, sin peticiones a terceros. Un nivel es una secuencia de pasos:</p>
<div class="types">
  <div><b>story</b><span>Texto corto con ícono: contexto, historia, explicación.</span></div>
  <div><b>quiz</b><span>Opción múltiple, con el porqué de cada alternativa.</span></div>
  <div><b>circuit</b><span>Desafío: arma un circuito que llegue al estado objetivo.</span></div>
  <div><b>measure</b><span>Mide un circuito muchas veces y mira surgir la estadística.</span></div>
  <div><b>predict</b><span>Adivina la probabilidad antes de ver la respuesta.</span></div>
  <div><b>fact</b><span>Una curiosidad para recordar después.</span></div>
</div>
<p>Las puertas se escriben como texto — <code>"H 0"</code>, <code>"CNOT 0 1"</code> — y el validador del repositorio ejecuta la solución de referencia de cada desafío en el mismo simulador del juego. Ningún nivel publicado es imposible. Las traducciones viven en <code>i18n/</code> y solo cambian el texto: la física es la misma en todos los idiomas.</p>
<h2>Convenciones</h2>
<p>El hilo de arriba es el qubit 0 y es el dígito de más a la izquierda: en <code>|10⟩</code>, el qubit 0 vale 1. En las barras de probabilidad, el <strong>color</strong> muestra la fase de cada amplitud; en las esferas, una flecha corta significa que el qubit está entrelazado con los demás.</p>
<h2>Contribuye</h2>
<p>¿Docente, estudiante o investigador(a)? Escribe un nivel o traduce uno. El paso a paso está en <code>docs/CONTRIBUTING.md</code>, en el <a href="https://github.com/2T0nnks/Cheshire" rel="noopener">repositorio de GitHub</a>.</p>
<h2>Privacidad</h2>
<p>Tu progreso se queda solo en tu navegador (localStorage). No se envía nada a ningún lado.</p>
<p><button class="btn small" data-action="reset-progress">Borrar mi progreso</button></p>
<h2>Licencias</h2>
<p>Código del motor bajo MIT; contenido de los niveles y documentación bajo CC BY-SA 4.0. Fuentes Space Grotesk, Atkinson Hyperlegible y JetBrains Mono bajo SIL OFL.</p>`,
    resetConfirm: "¿Borrar todo tu progreso en este navegador?",
    resetDone: "Progreso borrado.",
    footerLeftHtml: "Cheshire · aprende cuántica jugando · <a href=\"https://github.com/2T0nnks/Cheshire\" rel=\"noopener\">código en GitHub</a>",
    footerRight: "Hecho con qubits simulados y mucho café ☕",

    petAria: "Gato de Cheshire — haz clic para oír una curiosidad",
    petHide: "Esconder al Gato",
    petShow: "Mostrar al Gato",
    petBack: "¡Volví! En realidad, nunca me fui.",
    petGreet: ["¡Hola! ¿Por dónde empezar? Depende de adónde quieras llegar.", "Bienvenido. Aquí nada es solo una cosa u otra — hasta que alguien mira.", "Elige un nivel. Te acompaño… a veces solo con la sonrisa."],
    petLab: "¡Laboratorio libre! Nada puede salir mal. Bueno… casi nada.",
    petStart: ["{0} {1}. ¡Vamos!", "Ah, “{1}”. Uno de mis favoritos.", "Sigue al conejo. O al circuito."],
    petQuizRight: ["¡Sí! Sonrío de oreja a oreja.", "Exacto. Hasta aparecí entero de alegría.", "En el blanco. Eres bueno en esto."],
    petQuizLate: "Ahí está. Equivocarse es parte de la superposición.",
    petQuizWrong: ["Mmm, esta vez no. Lee el porqué — te espero.", "¡Cada vez más curiosísimo! Prueba otra.", "No todo es lo que parece. Inténtalo de nuevo."],
    petGaveUp: "Estudia este circuito con calma. La próxima es tuya.",
    petFewer: "¡¿Menos puertas que la solución oficial?! Hasta me volví visible de la sorpresa.",
    petSolved: ["El Gato sonríe: ¡objetivo alcanzado!", "Qué circuito tan elegante.", "Perfecto. La flecha fue justo adonde debía."],
    petPhase: "Psst: las barras coinciden, pero el color no. ¡Es la fase!",
    petHint: "Psst… dejé una pista justo debajo del circuito.",
    petMeasure: "¡Cayó! Antes de medir, ni yo sabía el resultado.",
    petPredict1: "¡Qué intuición cuántica! Estoy impresionado.",
    petPredict05: "Cerca. La cuántica engaña a todo el mundo.",
    petPredict0: "¿Sorprendido? Yo también, la primera vez.",
    petFinish3: "¡Tres estrellas! Lo sabía — o estaba en superposición de saberlo.",
    petFinish: "¡Nivel completado! ¿Vas por las tres estrellas?",
    petLang: "Ahora hablo español. Un gato políglota, quién lo diría.",
    petQuips: [
      "Aquí todos estamos un poco superpuestos. Tú también, hasta que alguien mire.",
      "¿Adónde quieres llegar? Eso depende mucho del circuito que armes.",
      "He visto muchos gatos sin sonrisa. ¿Pero un qubit sin fase? Nunca.",
      "Si desaparezco, no te preocupes: es solo decoherencia.",
      "¡Cada vez más curiosísimo! Así se aprende cuántica.",
      "Dos H seguidas se deshacen. El Sombrerero y yo también, después del té.",
    ],
  };

  const en = {
    skip: "Skip to content",
    brandAria: "Cheshire — home",
    navAria: "Main",
    navHome: "Levels",
    navLab: "Lab",
    navGlossary: "Glossary",
    navAbout: "About",
    xpTitle: "Experience points",
    themeToLight: "Switch to light theme",
    themeToDark: "Switch to dark theme",
    menuOpen: "Open menu",
    langAria: "Language",
    titleHome: "Cheshire — hands-on quantum physics",
    titleSuffix: "{0} · Cheshire",

    heroKicker: "⚛ educational mini-game · open source",
    heroTitleHtml: "Quantum physics, <em>hands-on</em>.",
    heroLede: "Build circuits, measure qubits and watch interference happen. Short levels for the merely curious and for those who want to go deep.",
    heroLab: "Open the lab",
    heroSphereAria: "Animated Bloch sphere: a spinning arrow represents the state of a qubit",
    ctaStart: "Start the first level",
    ctaContinue: "Continue: {0}",
    ctaResume: "Resume: {0} (step {1})",
    ctaReview: "Review the levels",
    homeWho: "For whom?",
    homeAudAria: "Filter levels by audience",
    homeLevels: "levels",
    homeStars: "stars",
    homeTrack: "track {0}",
    homeSoon: "coming soon",
    homeNext: "next",
    homeInProgress: "in progress",
    homeNone: "No levels for this audience yet. How about writing one?",
    cardStars: ", {0} stars",
    dykTitle: "Did you know?",
    dykNext: "Another fun fact",
    dykFrom: "From the level ",
    starsOf: "{0} of 3 stars",

    tracks: {
      fundamentos: ["Fundamentals", "Qubits, measurement and the basic weirdness."],
      circuitos: ["Circuits", "Gates, phase, interference and entanglement in practice."],
      fenomenos: ["Phenomena", "Real quantum physics experiments, as circuits."],
      algoritmos: ["Algorithms & protocols", "What you can do with all of this."],
    },
    audience: {
      todos: ["All", "Every level, in the suggested order.", "All"],
      curioso: ["🌱 Curious", "No prerequisites. Just curiosity.", "Curious"],
      estudante: ["📘 Student", "High school or college: a bit of vectors and angles helps.", "Student"],
      avancado: ["🚀 Advanced", "For devs and researchers: algorithms and protocols.", "Advanced"],
    },
    gates: {
      H: ["Hadamard", "creates superposition — swaps the poles for the equator."],
      X: ["Pauli-X", "the quantum NOT — swaps 0 and 1."],
      Y: ["Pauli-Y", "a half turn around the Y axis."],
      Z: ["Pauli-Z", "flips the phase of |1⟩ (a half turn around the equator)."],
      S: ["Phase S", "rotates the phase of |1⟩ by 90°."],
      T: ["Phase T", "rotates the phase of |1⟩ by 45°."],
      SDG: ["S dagger", "rotates the phase by −90°."],
      TDG: ["T dagger", "rotates the phase by −45°."],
      CNOT: ["Controlled NOT", "if the control (●) is 1, applies X to the target (⊕)."],
      CZ: ["Controlled Z", "flips the sign of |11⟩."],
      SWAP: ["Swap", "swaps the states of two qubits."],
    },

    legendTitle: "Each bar's color shows the phase of its amplitude",
    legend: "color = phase",
    stateNow: "Current state",
    ketAria: "State in Dirac notation",
    ghostNote: "Dashed outline = target.",
    targetTitle: "Target: {0}",
    sphereOne: "Bloch sphere",
    spherePerQubit: "One qubit at a time",
    entangled: "entangled",
    arrowLen: "arrow {0}%",
    blochAria: "Bloch sphere: x {0}, y {1}, z {2}",

    paletteAria: "Available gates",
    boardAria: "Quantum circuit",
    clear: "Clear",
    pendingHtml: "<b>{0}</b>: now click the <b>{1}</b> wire, in the same column. <span class=\"dim\">Esc cancels.</span>",
    pendingTarget: "target (⊕)",
    pendingSecond: "second qubit",
    helpTwo2: "Click the control wire; the other wire becomes the target.",
    helpTwoN: "Click the control wire, then the target.",
    helpOne: "Click a spot on a wire.",
    helpNone: "Pick a gate above. Click a placed gate to remove it.",
    gateLocked: "That gate is part of the challenge and can't be removed.",
    pickFirst: "Pick a gate from the palette first.",
    wireBusy: "The other wire is already taken in this column.",
    cellEmpty: "{0}, column {1}: empty",
    cellGate: "{0}, column {1}: {2}",
    cellFixed: " (fixed)",
    cellRemove: " — click to remove",
    gateCount1: "{0} gate",
    gateCountN: "{0} gates",

    playerBack: "← Levels",
    playerBackAria: "Back to the level map",
    stepEnd: "end",
    next: "Continue",
    nextFinish: "Finish level",
    nextOver: "Level over",
    resumed: "Resuming from step {0}.",
    kickerQuiz: "Question",
    kickerCircuit: "Challenge",
    kickerMeasure: "Experiment",
    kickerPredict: "Guess",
    factSource: "Source: {0}",
    quizFirst: "First try! +1 point",
    quizAfter: "That's it! Now you know why.",
    quizWrong: "Almost! Read why and try another.",
    goalTag: "Target",
    yourCircuit: "Your circuit",
    solvedGaveUp: "Solution applied. Study the circuit and move on.",
    solvedFewer: "Solved with {0} gates — fewer than our solution! 🤯",
    solvedPerfect: "Solved on the first try, with the fewest gates! ✨",
    solved: "Solved!",
    solvedMore1: "Solved! It can be done with {0} gate.",
    solvedMoreN: "Solved! It can be done with {0} gates.",
    targetHit: "Target reached. ",
    phaseOffHtml: "The probabilities match… but the <strong>phase</strong> doesn't. Look at the bar colors and the sphere.",
    fidelity: "Getting close? Fidelity with the target: {0}%",
    hint: "💡 Hint",
    hintN: "💡 Hint ({0}/{1})",
    hintSolution: "🔓 Show solution",
    hintLabel: "Hint {0}: ",
    measureNone: "No measurements yet.",
    measureSeqAria: "Latest results",
    measureOne: "The qubit “landed” on this result.",
    measureMany: "Last of {0} results.",
    measureDone: "Keep measuring as much as you like — or move on.",
    measureReset: "Reset",
    measureCleared: "Counts reset.",
    measure1: "Measure 1×",
    theCircuit: "The circuit",
    measurements: "Measurements",
    measureShortcut: "shortcut: space",
    progress: "Progress",
    measureExpected: "Dashed = what theory predicts. The more you measure, the closer the bars get to it.",
    predictAny: "{0} (· = any)",
    predictConfirm: "Lock in my guess",
    predictAria: "Your guess, in percent",
    verdict1: "Bullseye! 🎯",
    verdict2: "Very close! 👏",
    verdict3: "Close.",
    verdict4: "Surprised? 😮",
    predictYours: "Your guess: {0}",
    predictAnswer: "Answer: {0}",
    predictP1: "+1 point for quantum intuition",
    predictP05: "+½ point",
    predictP0: "No point this time — but now you know!",
    predictChance: "What are the odds?",
    predictOf: "of measuring {0}",
    finishMastered: "Level mastered!",
    finishDone: "Level complete!",
    finishRecord: "{0} XP (your best is {1})",
    finishTake: "Key takeaways",
    finishTerms: "Terms in this level",
    finishFurther: "Go further",
    finishNext: "Next: {0}",
    finishAgain: "Play again",
    finishMap: "Level map",
    finishThree: "Three stars! ⭐⭐⭐",
    finishTip: "Tip: get it right on the first try and use fewer gates for more stars.",

    labTitle: "Free lab",
    labDesc: "No goal, no grade: build any circuit you like (up to 4 qubits) and watch the state change in real time. Great for testing ideas from the levels.",
    labLoad: "Load example",
    labLess: "Fewer qubits",
    labMore: "More qubits",
    labQ1: "{0} qubit",
    labQN: "{0} qubits",
    presets: {
      vazio: "Empty circuit", bell: "Bell pair", ghz: "GHZ (3 qubits)", interferencia: "Interference (H·Z·H)",
      grover: "Grover (marks |11⟩)", teleporte: "Teleportation",
    },
    glossTitle: "Glossary",
    glossDesc: "The words that show up in the levels, explained without formulas (almost).",
    glossSearch: "Search a term…",
    glossSearchAria: "Search the glossary",
    glossNone: "Nothing found.",
    aboutTitle: "About Cheshire",
    aboutLede: "An open mini-game to teach quantum computing and physics to different people, at different levels — from “never heard of it” to “I want to understand Grover”.",
    aboutHtml: `
<h2>Why “Cheshire”?</h2>
<p>In <em>Alice's Adventures in Wonderland</em> (Lewis Carroll, 1865), the Cheshire Cat fades away until only its grin is left — and Alice remarks that she has often seen a cat without a grin, but never a grin without a cat. Here it's your companion: it comments on your moves, drops hints and, if you sit still, vanishes and leaves only the grin. Click it to hear a fun fact.</p>
<p>Physics has one too: in 2013, Aharonov, Popescu, Rohrlich and Skrzypczyk proposed the <strong>quantum Cheshire cat</strong> — in an interferometer, weak measurements suggest the particle took one path and its spin took the other. The effect was observed with neutrons in 2014, and what it means is still debated.</p>
<p><button class="btn small" data-action="pet-toggle"></button></p>
<h2>And the spinning sphere?</h2>
<p>It's the Bloch sphere, named after Felix Bloch: the prettiest way to picture a qubit. In every challenge, the spinning arrow you see is it.</p>
<h2>How levels work</h2>
<p>Each level is a single JSON file in the repository's <code>levels/</code> folder. The engine reads those files at build time and bundles everything into one HTML file — no server, no trackers, no third-party requests. A level is a sequence of steps:</p>
<div class="types">
  <div><b>story</b><span>Short text with an icon: context, history, explanation.</span></div>
  <div><b>quiz</b><span>Multiple choice, with the why behind every option.</span></div>
  <div><b>circuit</b><span>Challenge: build a circuit that reaches the target state.</span></div>
  <div><b>measure</b><span>Measure a circuit many times and watch the statistics emerge.</span></div>
  <div><b>predict</b><span>Guess the probability before seeing the answer.</span></div>
  <div><b>fact</b><span>A fun fact to remember later.</span></div>
</div>
<p>Gates are written as text — <code>"H 0"</code>, <code>"CNOT 0 1"</code> — and the repository's validator runs every challenge's reference solution through the same simulator the game uses. No published level is impossible. Translations live in <code>i18n/</code> and only change the text: the physics is the same in every language.</p>
<h2>Conventions</h2>
<p>The top wire is qubit 0 and it's the leftmost digit: in <code>|10⟩</code>, qubit 0 is 1. In the probability bars, the <strong>color</strong> shows each amplitude's phase; on the spheres, a short arrow means the qubit is entangled with the others.</p>
<h2>Contribute</h2>
<p>Teacher, student or researcher? Write a level or translate one. The step-by-step guide is in <code>docs/CONTRIBUTING.md</code>, in the <a href="https://github.com/2T0nnks/Cheshire" rel="noopener">GitHub repository</a>.</p>
<h2>Privacy</h2>
<p>Your progress stays in your browser only (localStorage). Nothing is sent anywhere.</p>
<p><button class="btn small" data-action="reset-progress">Erase my progress</button></p>
<h2>Licenses</h2>
<p>Engine code under MIT; level content and documentation under CC BY-SA 4.0. Space Grotesk, Atkinson Hyperlegible and JetBrains Mono fonts under the SIL OFL.</p>`,
    resetConfirm: "Erase all your progress in this browser?",
    resetDone: "Progress erased.",
    footerLeftHtml: "Cheshire · learn quantum by playing · <a href=\"https://github.com/2T0nnks/Cheshire\" rel=\"noopener\">code on GitHub</a>",
    footerRight: "Made with simulated qubits and lots of coffee ☕",

    petAria: "Cheshire Cat — click to hear a fun fact",
    petHide: "Hide the Cat",
    petShow: "Show the Cat",
    petBack: "I'm back! I never really left.",
    petGreet: ["Hi! Where to start? That depends a good deal on where you want to get to.", "Welcome. Here nothing is just one thing or the other — until someone looks.", "Pick a level. I'll come along… sometimes just my grin."],
    petLab: "The free lab! Nothing can go wrong. Well… almost nothing.",
    petStart: ["{0} {1}. Let's go!", "Ah, “{1}”. One of my favorites.", "Follow the rabbit. Or the circuit."],
    petQuizRight: ["Yes! Grinning from ear to ear.", "Exactly. I fully appeared out of sheer joy.", "Spot on. You're good at this."],
    petQuizLate: "There you go. Being wrong is part of the superposition.",
    petQuizWrong: ["Hmm, not this time. Read why — I'll wait.", "Curiouser and curiouser! Try another.", "Not everything is what it seems. Try again."],
    petGaveUp: "Study this circuit calmly. Next time, it's yours.",
    petFewer: "Fewer gates than the official solution?! I became visible out of surprise.",
    petSolved: ["The Cat grins: target reached!", "What an elegant circuit.", "Perfect. The arrow went exactly where it should."],
    petPhase: "Psst: the bars match, but the color doesn't. It's the phase!",
    petHint: "Psst… I left a hint right below the circuit.",
    petMeasure: "It landed! Before measuring, not even I knew the result.",
    petPredict1: "What quantum intuition! I'm impressed.",
    petPredict05: "Close. Quantum fools everyone.",
    petPredict0: "Surprised? So was I, the first time.",
    petFinish3: "Three stars! I knew it — or I was in a superposition of knowing.",
    petFinish: "Level complete! Want to go for three stars?",
    petLang: "Now I speak English. A polyglot cat, who knew.",
    petQuips: [
      "We're all a little superposed here. You too, until someone looks.",
      "Where do you want to get to? That depends a good deal on the circuit you build.",
      "I've often seen a cat without a grin. But a qubit without a phase? Never.",
      "If I vanish, don't worry: it's just decoherence.",
      "Curiouser and curiouser! That's how you learn quantum.",
      "Two H's in a row undo each other. So do the Hatter and I, after tea.",
    ],
  };

  root.STRINGS = { LANGS, pt, es, en };
})(typeof globalThis !== "undefined" ? globalThis : this);
